<<<<<<< Updated upstream
echo Press any button to continue auto-setup of this device. (created by Eric Shao)
Pause >nul
powershell -ExecutionPolicy Bypass -File "%~dp000RTTandCreateShortCut.ps1"
echo Debloating stuff...
powershell -ExecutionPolicy Bypass -File "%~dp0Windows10Debloater-master\Windows10DebloaterGUI.ps1"
echo Creating a new user...
powershell -ExecutionPolicy Bypass -File "%~dp0CreateNewUser.ps1"
echo Updating Windows and Setting Auto Updates...
powershell -ExecutionPolicy Bypass -File "%~dp0WindowsAutoUpdateRema.ps1"
echo Installing Printer Stuff...
powershell -ExecutionPolicy Bypass -File "%~dp0PrinterSetup.ps1"
echo Installing all the software needed...
powershell -ExecutionPolicy Bypass -File "%~dp0SoftwareInstall.ps1"
echo Creating System Restore Point...
powershell -ExecutionPolicy Bypass -File "%~dp0SystemRestorePoint.ps1"
echo Finished everything. Press any key to exit.
Pause >nul
=======
echo Press any button to continue auto-setup of this device. (created by Eric Shao)
Pause >nul
powershell -ExecutionPolicy Bypass -File "%~dp0Powershell-Scripts\00RTTandCreateShortCut.ps1"
echo Debloating stuff...
powershell -ExecutionPolicy Bypass -File "%~dp0Windows10Debloater-master\Windows10DebloaterGUI.ps1"
echo Creating a new user...
powershell -ExecutionPolicy Bypass -File "%~dp0Powershell-Scripts\CreateNewUser.ps1"
echo Updating Windows and Setting Auto Updates...
powershell -ExecutionPolicy Bypass -File "%~dp0Powershell-Scripts\WindowsAutoUpdateRema.ps1"
echo Installing Printer Stuff...
powershell -ExecutionPolicy Bypass -File "%~dp0Powershell-Scripts\PrinterSetup.ps1"
echo Installing all the software needed...
powershell -ExecutionPolicy Bypass -File "%~dp0Powershell-Scripts\SoftwareInstall.ps1"
echo Creating System Restore Point...
powershell -ExecutionPolicy Bypass -File "%~dp0Powershell-Scripts\SystemRestorePoint.ps1"
echo Finished everything. Press any key to exit.
Pause >nul
>>>>>>> Stashed changes
